target 'TargetProject' do
  platform :ios, '9.0'
  use_frameworks!
  pod 'BeacrewLoco', :path => 'BeacrewLoco'
  pod 'Realm', '= 2.10.2'
  pod 'MQTTClient', '= 0.9.9'
  pod 'OpenSSL-Universal', '= 1.0.2.10'
end
